default_stages: [commit]
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
        args: ["--unsafe"]
        files: src/
      - id: end-of-file-fixer
        files: src/
      - id: trailing-whitespace
        files: src/
      - id: check-added-large-files
        files: src/
        args: ["--maxkb=10000"]
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.990
    hooks:
      - id: mypy
        args: ["--ignore-missing-imports"]
        additional_dependencies:
          - "types-requests"
          - "types-PyYAML"
        files: "src/.*|tests/.*"
-   repo: https://github.com/timothycrosley/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort (python)
        args: ["--line-length=80"]
        files: "src/.*|tests/.*"
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.2.2
    hooks:
      - id: ruff
        args: [--fix]
        exclude: notebooks/
      - id: ruff-format
        exclude: notebooks/
-   repo: local
    hooks:
      - id: pytest
        name: pytest-check
        entry: pytest tests/
        language: system
        pass_filenames: false
        always_run: true
        stages: [push]
  